declare const _exports: {
    config: {
        maxMemorySize: any;
        maxMemoryItems: any;
        defaultTTL: any;
        redisEnabled: boolean;
        redisHost: any;
        redisPort: any;
        redisPassword: any;
        compressionEnabled: boolean;
        compressionThreshold: any;
        warmingEnabled: boolean;
        namespace: any;
    };
    memoryCache: Map<any, any>;
    memoryCacheMetadata: Map<any, any>;
    redisClient: any;
    redisConnected: boolean;
    stats: {
        hits: number;
        misses: number;
        sets: number;
        dels: number;
        evictions: number;
        errors: number;
        memoryHits: number;
        redisHits: number;
        totalLatency: number;
        requestCount: number;
    };
    cleanupInterval: NodeJS.Timeout;
    init(): Promise<void>;
    initRedis(): Promise<void>;
    get(key: any, options?: {}): Promise<any>;
    set(key: any, value: any, options?: {}): Promise<boolean>;
    del(key: any, options?: {}): Promise<boolean>;
    invalidatePattern(pattern: any, options?: {}): Promise<number>;
    clear(options?: {}): Promise<boolean>;
    getFromMemory(key: any): any;
    setInMemory(key: any, value: any, options?: {}): void;
    getFromRedis(key: any): Promise<any>;
    setInRedis(key: any, value: any, options?: {}): Promise<void>;
    evictLRU(): void;
    cleanupExpired(): void;
    warmCache(): Promise<void>;
    buildKey(key: any, namespace: any): string;
    matchPattern(str: any, pattern: any): boolean;
    estimateSize(value: any): number;
    updateLatency(startTime: any): void;
    getStats(): {
        hits: number;
        misses: number;
        hitRate: string;
        memoryHits: number;
        redisHits: number;
        sets: number;
        dels: number;
        evictions: number;
        errors: number;
        avgLatency: string;
        requestCount: number;
        memorySize: number;
        memoryUsage: string;
        redisConnected: boolean;
    };
    resetStats(): void;
    disconnect(): Promise<void>;
};
export = _exports;
//# sourceMappingURL=cacheManager.d.ts.map