export class ParentTeacherCommunicationService {
    conversationsFile: string;
    appointmentsFile: string;
    messagesFile: string;
    reportsFile: string;
    conversations: Map<any, any>;
    appointments: Map<any, any>;
    messages: Map<any, any>;
    academicReports: Map<any, any>;
    init(): Promise<void>;
    ensureDataDirectory(): Promise<void>;
    loadData(): Promise<void>;
    createSampleData(): void;
    createConversation(data: any): Promise<{
        id: any;
        student_id: any;
        student_name: any;
        parent_id: any;
        parent_name: any;
        teacher_id: any;
        teacher_name: any;
        subject: any;
        status: string;
        created_at: string;
        updated_at: string;
        last_message: any;
    }>;
    getConversations(userId: any, userType: any): Promise<any[]>;
    getConversationById(conversationId: any): Promise<any>;
    updateConversation(conversationId: any, updates: any): Promise<any>;
    sendMessage(data: any): Promise<{
        id: any;
        conversation_id: any;
        sender_id: any;
        sender_type: any;
        sender_name: any;
        recipient_id: any;
        recipient_type: any;
        content: any;
        message_type: any;
        read: boolean;
        timestamp: string;
        attachments: any;
    }>;
    getMessages(conversationId: any, limit?: number, offset?: number): Promise<any[]>;
    markMessageAsRead(messageId: any, userId: any): Promise<boolean>;
    markConversationAsRead(conversationId: any, userId: any): Promise<number>;
    scheduleAppointment(data: any): Promise<{
        id: any;
        student_id: any;
        student_name: any;
        parent_id: any;
        parent_name: any;
        teacher_id: any;
        teacher_name: any;
        subject: any;
        appointment_date: any;
        duration_minutes: any;
        meeting_type: any;
        meeting_link: any;
        status: string;
        agenda: any;
        created_at: string;
        notes: string;
    }>;
    getAppointments(userId: any, userType: any, filters?: {}): Promise<any[]>;
    updateAppointment(appointmentId: any, updates: any): Promise<any>;
    cancelAppointment(appointmentId: any, cancelledBy: any): Promise<any>;
    createAcademicReport(data: any): Promise<{
        id: any;
        student_id: any;
        student_name: any;
        teacher_id: any;
        teacher_name: any;
        subject: any;
        period: any;
        report_type: any;
        content: any;
        created_at: string;
        shared_with_parent: any;
        parent_feedback: any;
    }>;
    getAcademicReports(userId: any, userType: any, filters?: {}): Promise<any[]>;
    addParentFeedback(reportId: any, parentId: any, feedback: any): Promise<any>;
    isParentOfStudent(parentId: any, studentId: any): any;
    getUnreadMessagesCount(userId: any): Promise<number>;
    getUpcomingAppointments(userId: any, userType: any, days?: number): Promise<any[]>;
    getCommunicationStats(userId: any, userType: any): Promise<{
        total_conversations: number;
        active_conversations: number;
        unread_messages: number;
        upcoming_appointments: number;
        last_activity: any;
    }>;
    saveConversations(): Promise<void>;
    saveAppointments(): Promise<void>;
    saveMessages(): Promise<void>;
    saveReports(): Promise<void>;
    saveAllData(): Promise<void>;
}
export function getParentTeacherCommunicationService(): any;
//# sourceMappingURL=parentTeacherCommunicationService.d.ts.map