declare const _exports: {
    queues: Map<any, any>;
    processingMap: Map<any, any>;
    createQueue(name: any, options?: {}): any;
    add(queueName: any, data: any, options?: {}): Promise<{
        id: string;
        data: any;
        attempts: number;
        maxAttempts: any;
        priority: any;
        delay: any;
        createdAt: number;
        status: string;
    }>;
    process(queueName: any, processor: any): void;
    processQueue(queueName: any): Promise<void>;
    getStats(queueName: any): any;
    clear(queueName: any): void;
    [EventEmitter.captureRejectionSymbol]?<K>(error: Error, event: string | symbol, ...args: any[]): void;
    addListener<K>(eventName: string | symbol, listener: (...args: any[]) => void): {
        queues: Map<any, any>;
        processingMap: Map<any, any>;
        createQueue(name: any, options?: {}): any;
        add(queueName: any, data: any, options?: {}): Promise<{
            id: string;
            data: any;
            attempts: number;
            maxAttempts: any;
            priority: any;
            delay: any;
            createdAt: number;
            status: string;
        }>;
        process(queueName: any, processor: any): void;
        processQueue(queueName: any): Promise<void>;
        getStats(queueName: any): any;
        clear(queueName: any): void;
        [EventEmitter.captureRejectionSymbol]?<K_1>(error: Error, event: string | symbol, ...args: any[]): void;
        addListener<K>(eventName: string | symbol, listener: (...args: any[]) => void): /*elided*/ any;
        on<K_1>(eventName: string | symbol, listener: (...args: any[]) => void): /*elided*/ any;
        once<K_1>(eventName: string | symbol, listener: (...args: any[]) => void): /*elided*/ any;
        removeListener<K_1>(eventName: string | symbol, listener: (...args: any[]) => void): /*elided*/ any;
        off<K_1>(eventName: string | symbol, listener: (...args: any[]) => void): /*elided*/ any;
        removeAllListeners(eventName?: string | symbol): /*elided*/ any;
        setMaxListeners(n: number): /*elided*/ any;
        getMaxListeners(): number;
        listeners<K_1>(eventName: string | symbol): Function[];
        rawListeners<K_1>(eventName: string | symbol): Function[];
        emit<K_1>(eventName: string | symbol, ...args: any[]): boolean;
        listenerCount<K_1>(eventName: string | symbol, listener?: Function): number;
        prependListener<K_1>(eventName: string | symbol, listener: (...args: any[]) => void): /*elided*/ any;
        prependOnceListener<K_1>(eventName: string | symbol, listener: (...args: any[]) => void): /*elided*/ any;
        eventNames(): (string | symbol)[];
    };
    on<K>(eventName: string | symbol, listener: (...args: any[]) => void): {
        queues: Map<any, any>;
        processingMap: Map<any, any>;
        createQueue(name: any, options?: {}): any;
        add(queueName: any, data: any, options?: {}): Promise<{
            id: string;
            data: any;
            attempts: number;
            maxAttempts: any;
            priority: any;
            delay: any;
            createdAt: number;
            status: string;
        }>;
        process(queueName: any, processor: any): void;
        processQueue(queueName: any): Promise<void>;
        getStats(queueName: any): any;
        clear(queueName: any): void;
        [EventEmitter.captureRejectionSymbol]?<K_1>(error: Error, event: string | symbol, ...args: any[]): void;
        addListener<K_1>(eventName: string | symbol, listener: (...args: any[]) => void): /*elided*/ any;
        on<K>(eventName: string | symbol, listener: (...args: any[]) => void): /*elided*/ any;
        once<K_1>(eventName: string | symbol, listener: (...args: any[]) => void): /*elided*/ any;
        removeListener<K_1>(eventName: string | symbol, listener: (...args: any[]) => void): /*elided*/ any;
        off<K_1>(eventName: string | symbol, listener: (...args: any[]) => void): /*elided*/ any;
        removeAllListeners(eventName?: string | symbol): /*elided*/ any;
        setMaxListeners(n: number): /*elided*/ any;
        getMaxListeners(): number;
        listeners<K_1>(eventName: string | symbol): Function[];
        rawListeners<K_1>(eventName: string | symbol): Function[];
        emit<K_1>(eventName: string | symbol, ...args: any[]): boolean;
        listenerCount<K_1>(eventName: string | symbol, listener?: Function): number;
        prependListener<K_1>(eventName: string | symbol, listener: (...args: any[]) => void): /*elided*/ any;
        prependOnceListener<K_1>(eventName: string | symbol, listener: (...args: any[]) => void): /*elided*/ any;
        eventNames(): (string | symbol)[];
    };
    once<K>(eventName: string | symbol, listener: (...args: any[]) => void): {
        queues: Map<any, any>;
        processingMap: Map<any, any>;
        createQueue(name: any, options?: {}): any;
        add(queueName: any, data: any, options?: {}): Promise<{
            id: string;
            data: any;
            attempts: number;
            maxAttempts: any;
            priority: any;
            delay: any;
            createdAt: number;
            status: string;
        }>;
        process(queueName: any, processor: any): void;
        processQueue(queueName: any): Promise<void>;
        getStats(queueName: any): any;
        clear(queueName: any): void;
        [EventEmitter.captureRejectionSymbol]?<K_1>(error: Error, event: string | symbol, ...args: any[]): void;
        addListener<K_1>(eventName: string | symbol, listener: (...args: any[]) => void): /*elided*/ any;
        on<K_1>(eventName: string | symbol, listener: (...args: any[]) => void): /*elided*/ any;
        once<K>(eventName: string | symbol, listener: (...args: any[]) => void): /*elided*/ any;
        removeListener<K_1>(eventName: string | symbol, listener: (...args: any[]) => void): /*elided*/ any;
        off<K_1>(eventName: string | symbol, listener: (...args: any[]) => void): /*elided*/ any;
        removeAllListeners(eventName?: string | symbol): /*elided*/ any;
        setMaxListeners(n: number): /*elided*/ any;
        getMaxListeners(): number;
        listeners<K_1>(eventName: string | symbol): Function[];
        rawListeners<K_1>(eventName: string | symbol): Function[];
        emit<K_1>(eventName: string | symbol, ...args: any[]): boolean;
        listenerCount<K_1>(eventName: string | symbol, listener?: Function): number;
        prependListener<K_1>(eventName: string | symbol, listener: (...args: any[]) => void): /*elided*/ any;
        prependOnceListener<K_1>(eventName: string | symbol, listener: (...args: any[]) => void): /*elided*/ any;
        eventNames(): (string | symbol)[];
    };
    removeListener<K>(eventName: string | symbol, listener: (...args: any[]) => void): {
        queues: Map<any, any>;
        processingMap: Map<any, any>;
        createQueue(name: any, options?: {}): any;
        add(queueName: any, data: any, options?: {}): Promise<{
            id: string;
            data: any;
            attempts: number;
            maxAttempts: any;
            priority: any;
            delay: any;
            createdAt: number;
            status: string;
        }>;
        process(queueName: any, processor: any): void;
        processQueue(queueName: any): Promise<void>;
        getStats(queueName: any): any;
        clear(queueName: any): void;
        [EventEmitter.captureRejectionSymbol]?<K_1>(error: Error, event: string | symbol, ...args: any[]): void;
        addListener<K_1>(eventName: string | symbol, listener: (...args: any[]) => void): /*elided*/ any;
        on<K_1>(eventName: string | symbol, listener: (...args: any[]) => void): /*elided*/ any;
        once<K_1>(eventName: string | symbol, listener: (...args: any[]) => void): /*elided*/ any;
        removeListener<K>(eventName: string | symbol, listener: (...args: any[]) => void): /*elided*/ any;
        off<K_1>(eventName: string | symbol, listener: (...args: any[]) => void): /*elided*/ any;
        removeAllListeners(eventName?: string | symbol): /*elided*/ any;
        setMaxListeners(n: number): /*elided*/ any;
        getMaxListeners(): number;
        listeners<K_1>(eventName: string | symbol): Function[];
        rawListeners<K_1>(eventName: string | symbol): Function[];
        emit<K_1>(eventName: string | symbol, ...args: any[]): boolean;
        listenerCount<K_1>(eventName: string | symbol, listener?: Function): number;
        prependListener<K_1>(eventName: string | symbol, listener: (...args: any[]) => void): /*elided*/ any;
        prependOnceListener<K_1>(eventName: string | symbol, listener: (...args: any[]) => void): /*elided*/ any;
        eventNames(): (string | symbol)[];
    };
    off<K>(eventName: string | symbol, listener: (...args: any[]) => void): {
        queues: Map<any, any>;
        processingMap: Map<any, any>;
        createQueue(name: any, options?: {}): any;
        add(queueName: any, data: any, options?: {}): Promise<{
            id: string;
            data: any;
            attempts: number;
            maxAttempts: any;
            priority: any;
            delay: any;
            createdAt: number;
            status: string;
        }>;
        process(queueName: any, processor: any): void;
        processQueue(queueName: any): Promise<void>;
        getStats(queueName: any): any;
        clear(queueName: any): void;
        [EventEmitter.captureRejectionSymbol]?<K_1>(error: Error, event: string | symbol, ...args: any[]): void;
        addListener<K_1>(eventName: string | symbol, listener: (...args: any[]) => void): /*elided*/ any;
        on<K_1>(eventName: string | symbol, listener: (...args: any[]) => void): /*elided*/ any;
        once<K_1>(eventName: string | symbol, listener: (...args: any[]) => void): /*elided*/ any;
        removeListener<K_1>(eventName: string | symbol, listener: (...args: any[]) => void): /*elided*/ any;
        off<K>(eventName: string | symbol, listener: (...args: any[]) => void): /*elided*/ any;
        removeAllListeners(eventName?: string | symbol): /*elided*/ any;
        setMaxListeners(n: number): /*elided*/ any;
        getMaxListeners(): number;
        listeners<K_1>(eventName: string | symbol): Function[];
        rawListeners<K_1>(eventName: string | symbol): Function[];
        emit<K_1>(eventName: string | symbol, ...args: any[]): boolean;
        listenerCount<K_1>(eventName: string | symbol, listener?: Function): number;
        prependListener<K_1>(eventName: string | symbol, listener: (...args: any[]) => void): /*elided*/ any;
        prependOnceListener<K_1>(eventName: string | symbol, listener: (...args: any[]) => void): /*elided*/ any;
        eventNames(): (string | symbol)[];
    };
    removeAllListeners(eventName?: string | symbol): {
        queues: Map<any, any>;
        processingMap: Map<any, any>;
        createQueue(name: any, options?: {}): any;
        add(queueName: any, data: any, options?: {}): Promise<{
            id: string;
            data: any;
            attempts: number;
            maxAttempts: any;
            priority: any;
            delay: any;
            createdAt: number;
            status: string;
        }>;
        process(queueName: any, processor: any): void;
        processQueue(queueName: any): Promise<void>;
        getStats(queueName: any): any;
        clear(queueName: any): void;
        [EventEmitter.captureRejectionSymbol]?<K>(error: Error, event: string | symbol, ...args: any[]): void;
        addListener<K>(eventName: string | symbol, listener: (...args: any[]) => void): /*elided*/ any;
        on<K>(eventName: string | symbol, listener: (...args: any[]) => void): /*elided*/ any;
        once<K>(eventName: string | symbol, listener: (...args: any[]) => void): /*elided*/ any;
        removeListener<K>(eventName: string | symbol, listener: (...args: any[]) => void): /*elided*/ any;
        off<K>(eventName: string | symbol, listener: (...args: any[]) => void): /*elided*/ any;
        removeAllListeners(eventName?: string | symbol): /*elided*/ any;
        setMaxListeners(n: number): /*elided*/ any;
        getMaxListeners(): number;
        listeners<K>(eventName: string | symbol): Function[];
        rawListeners<K>(eventName: string | symbol): Function[];
        emit<K>(eventName: string | symbol, ...args: any[]): boolean;
        listenerCount<K>(eventName: string | symbol, listener?: Function): number;
        prependListener<K>(eventName: string | symbol, listener: (...args: any[]) => void): /*elided*/ any;
        prependOnceListener<K>(eventName: string | symbol, listener: (...args: any[]) => void): /*elided*/ any;
        eventNames(): (string | symbol)[];
    };
    setMaxListeners(n: number): {
        queues: Map<any, any>;
        processingMap: Map<any, any>;
        createQueue(name: any, options?: {}): any;
        add(queueName: any, data: any, options?: {}): Promise<{
            id: string;
            data: any;
            attempts: number;
            maxAttempts: any;
            priority: any;
            delay: any;
            createdAt: number;
            status: string;
        }>;
        process(queueName: any, processor: any): void;
        processQueue(queueName: any): Promise<void>;
        getStats(queueName: any): any;
        clear(queueName: any): void;
        [EventEmitter.captureRejectionSymbol]?<K>(error: Error, event: string | symbol, ...args: any[]): void;
        addListener<K>(eventName: string | symbol, listener: (...args: any[]) => void): /*elided*/ any;
        on<K>(eventName: string | symbol, listener: (...args: any[]) => void): /*elided*/ any;
        once<K>(eventName: string | symbol, listener: (...args: any[]) => void): /*elided*/ any;
        removeListener<K>(eventName: string | symbol, listener: (...args: any[]) => void): /*elided*/ any;
        off<K>(eventName: string | symbol, listener: (...args: any[]) => void): /*elided*/ any;
        removeAllListeners(eventName?: string | symbol): /*elided*/ any;
        setMaxListeners(n: number): /*elided*/ any;
        getMaxListeners(): number;
        listeners<K>(eventName: string | symbol): Function[];
        rawListeners<K>(eventName: string | symbol): Function[];
        emit<K>(eventName: string | symbol, ...args: any[]): boolean;
        listenerCount<K>(eventName: string | symbol, listener?: Function): number;
        prependListener<K>(eventName: string | symbol, listener: (...args: any[]) => void): /*elided*/ any;
        prependOnceListener<K>(eventName: string | symbol, listener: (...args: any[]) => void): /*elided*/ any;
        eventNames(): (string | symbol)[];
    };
    getMaxListeners(): number;
    listeners<K>(eventName: string | symbol): Function[];
    rawListeners<K>(eventName: string | symbol): Function[];
    emit<K>(eventName: string | symbol, ...args: any[]): boolean;
    listenerCount<K>(eventName: string | symbol, listener?: Function): number;
    prependListener<K>(eventName: string | symbol, listener: (...args: any[]) => void): {
        queues: Map<any, any>;
        processingMap: Map<any, any>;
        createQueue(name: any, options?: {}): any;
        add(queueName: any, data: any, options?: {}): Promise<{
            id: string;
            data: any;
            attempts: number;
            maxAttempts: any;
            priority: any;
            delay: any;
            createdAt: number;
            status: string;
        }>;
        process(queueName: any, processor: any): void;
        processQueue(queueName: any): Promise<void>;
        getStats(queueName: any): any;
        clear(queueName: any): void;
        [EventEmitter.captureRejectionSymbol]?<K_1>(error: Error, event: string | symbol, ...args: any[]): void;
        addListener<K_1>(eventName: string | symbol, listener: (...args: any[]) => void): /*elided*/ any;
        on<K_1>(eventName: string | symbol, listener: (...args: any[]) => void): /*elided*/ any;
        once<K_1>(eventName: string | symbol, listener: (...args: any[]) => void): /*elided*/ any;
        removeListener<K_1>(eventName: string | symbol, listener: (...args: any[]) => void): /*elided*/ any;
        off<K_1>(eventName: string | symbol, listener: (...args: any[]) => void): /*elided*/ any;
        removeAllListeners(eventName?: string | symbol): /*elided*/ any;
        setMaxListeners(n: number): /*elided*/ any;
        getMaxListeners(): number;
        listeners<K_1>(eventName: string | symbol): Function[];
        rawListeners<K_1>(eventName: string | symbol): Function[];
        emit<K_1>(eventName: string | symbol, ...args: any[]): boolean;
        listenerCount<K_1>(eventName: string | symbol, listener?: Function): number;
        prependListener<K>(eventName: string | symbol, listener: (...args: any[]) => void): /*elided*/ any;
        prependOnceListener<K_1>(eventName: string | symbol, listener: (...args: any[]) => void): /*elided*/ any;
        eventNames(): (string | symbol)[];
    };
    prependOnceListener<K>(eventName: string | symbol, listener: (...args: any[]) => void): {
        queues: Map<any, any>;
        processingMap: Map<any, any>;
        createQueue(name: any, options?: {}): any;
        add(queueName: any, data: any, options?: {}): Promise<{
            id: string;
            data: any;
            attempts: number;
            maxAttempts: any;
            priority: any;
            delay: any;
            createdAt: number;
            status: string;
        }>;
        process(queueName: any, processor: any): void;
        processQueue(queueName: any): Promise<void>;
        getStats(queueName: any): any;
        clear(queueName: any): void;
        [EventEmitter.captureRejectionSymbol]?<K_1>(error: Error, event: string | symbol, ...args: any[]): void;
        addListener<K_1>(eventName: string | symbol, listener: (...args: any[]) => void): /*elided*/ any;
        on<K_1>(eventName: string | symbol, listener: (...args: any[]) => void): /*elided*/ any;
        once<K_1>(eventName: string | symbol, listener: (...args: any[]) => void): /*elided*/ any;
        removeListener<K_1>(eventName: string | symbol, listener: (...args: any[]) => void): /*elided*/ any;
        off<K_1>(eventName: string | symbol, listener: (...args: any[]) => void): /*elided*/ any;
        removeAllListeners(eventName?: string | symbol): /*elided*/ any;
        setMaxListeners(n: number): /*elided*/ any;
        getMaxListeners(): number;
        listeners<K_1>(eventName: string | symbol): Function[];
        rawListeners<K_1>(eventName: string | symbol): Function[];
        emit<K_1>(eventName: string | symbol, ...args: any[]): boolean;
        listenerCount<K_1>(eventName: string | symbol, listener?: Function): number;
        prependListener<K_1>(eventName: string | symbol, listener: (...args: any[]) => void): /*elided*/ any;
        prependOnceListener<K>(eventName: string | symbol, listener: (...args: any[]) => void): /*elided*/ any;
        eventNames(): (string | symbol)[];
    };
    eventNames(): (string | symbol)[];
    readonly __esModule: boolean;
    default: {
        queues: Map<any, any>;
        processingMap: Map<any, any>;
        createQueue(name: any, options?: {}): any;
        add(queueName: any, data: any, options?: {}): Promise<{
            id: string;
            data: any;
            attempts: number;
            maxAttempts: any;
            priority: any;
            delay: any;
            createdAt: number;
            status: string;
        }>;
        process(queueName: any, processor: any): void;
        processQueue(queueName: any): Promise<void>;
        getStats(queueName: any): any;
        clear(queueName: any): void;
        [EventEmitter.captureRejectionSymbol]?<K>(error: Error, event: string | symbol, ...args: any[]): void;
        addListener<K>(eventName: string | symbol, listener: (...args: any[]) => void): /*elided*/ any;
        on<K>(eventName: string | symbol, listener: (...args: any[]) => void): /*elided*/ any;
        once<K>(eventName: string | symbol, listener: (...args: any[]) => void): /*elided*/ any;
        removeListener<K>(eventName: string | symbol, listener: (...args: any[]) => void): /*elided*/ any;
        off<K>(eventName: string | symbol, listener: (...args: any[]) => void): /*elided*/ any;
        removeAllListeners(eventName?: string | symbol): /*elided*/ any;
        setMaxListeners(n: number): /*elided*/ any;
        getMaxListeners(): number;
        listeners<K>(eventName: string | symbol): Function[];
        rawListeners<K>(eventName: string | symbol): Function[];
        emit<K>(eventName: string | symbol, ...args: any[]): boolean;
        listenerCount<K>(eventName: string | symbol, listener?: Function): number;
        prependListener<K>(eventName: string | symbol, listener: (...args: any[]) => void): /*elided*/ any;
        prependOnceListener<K>(eventName: string | symbol, listener: (...args: any[]) => void): /*elided*/ any;
        eventNames(): (string | symbol)[];
    };
};
export = _exports;
//# sourceMappingURL=queueService.d.ts.map