#!/bin/bash

# Mapear los archivos identificados con más información
declare -a files=(
"professional-forms.js"
"dashboard-manager-2025.js"
"admin-dashboard.js"
"citas-manager.js"
"appointments.js"
"admin-dashboard-executive.js"
"accessibility-auditor-system.js"
"academic-reports-manager.js"
"quality-assurance.js"
"polls-manager.js"
"intelligent-login-system.js"
"admin.bundle.js"
"forms.bundle.js"
"features.bundle.js"
"dynamic-teacher-loader.js"
"dynamic-finance-loader.js"
"digital-library-manager.js"
"bolsa-trabajo-dashboard.js"
"automated-testing-system.js"
"ai-progress-dashboard.js"
"advanced-personalization-system.js"
"accessibility-auditor.js"
"main.js"
"inscriptions-handler.js"
"citas-events.js"
"bolsa-trabajo-events.js"
"virtual-labs-system.js"
"dashboard-personalizer.js"
"gamification-system.js"
"ar-education-system.js"
"support-tickets-manager.js"
"inscriptions-client.js"
"dynamic-loader.js"
"approvals-manager.js"
"chatbot.js"
"cms-manager.js"
"admin-newsletters.js"
"student-dashboard.js"
"student-portal.js"
"student-auth.js"
"parent-portal.js"
"padres-events.js"
"ia-dashboard-access.js"
"google-auth-integration.js"
"unified-auth-system-v2.js"
"tenants-admin-manager.js"
"suscriptores-manager.js"
"solicitudes-manager.js"
"security-manager.js"
"pwa-advanced.js"
"push-notification-system.js"
"push-notification-manager.js"
"profile-manager.js"
"payment-system.js"
"payment-system-advanced.js"
"parent-teacher-communication.js"
"parent-teacher-chat.js"
"parent-manager.js"
"pagos-events.js"
"pagination-manager.js"
"notification-config-ui.js"
"mobile-student-dashboard.js"
"mobile-enhancements.js"
"mobile/mobile-student-dashboard.js"
"messaging-manager.js"
"main.bundle.js"
"lazy-loading-advanced.js"
"job-portal.js"
"interactive-calendar.js"
"integration/bge-dashboard-ejecutivo.js"
"integrated-calendar-manager.js"
"icon-check.js"
"grades-platform.js"
"grades-manager.js"
"global-search.js"
"external-integrations.js"
"external-integrations-COMPLETO.js"
"event-calendar.js"
"egresados-email-confirmation.js"
"e2e-testing-chrome-mcp.js"
"dynamic-student-loader.js"
"dynamic-stats-loader.js"
"download-center.js"
"descargas-events.js"
"core.bundle.js"
"content-generator-ai.js"
"competitions-system.js"
"collaborative-ai-system.js"
"cms-simple.js"
"bolsa-trabajo-manager.js"
"bolsa-trabajo-email-confirmation.js"
"bge-testing-system.js"
"bge-security-module.js"
"bge-security-manager.js"
"bge-pwa-module.js"
"bge-pwa-advanced.js"
"bge-push-notification-system.js"
"bge-performance-optimizer.js"
"bge-multi-tenant-system.js"
)

# Analizar y crear tabla con estadísticas
echo "Analizando archivos para riesgos XSS..."
for file in "${files[@]}"; do
  filepath="public/js/$file"
  if [ -f "$filepath" ]; then
    inner=$(grep -o "\.innerHTML\s*=" "$filepath" 2>/dev/null | wc -l)
    adj=$(grep -o "\.insertAdjacentHTML" "$filepath" 2>/dev/null | wc -l)
    dompurify=$(grep -c "DOMPurify" "$filepath" 2>/dev/null || echo 0)
    total=$((inner + adj))
    if [ "$total" -gt 0 ]; then
      echo "$total|$inner|$adj|$dompurify|$file"
    fi
  fi
done | sort -rn -t'|' -k1
