/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AcademyCredential } from "./AcademyCredential";
export type { Greeter } from "./Greeter";
export type { IACoin } from "./IACoin";
export type { StudentIdentity } from "./StudentIdentity";
