/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AcademyCredential__factory } from "./AcademyCredential__factory";
export { Greeter__factory } from "./Greeter__factory";
export { IACoin__factory } from "./IACoin__factory";
export { StudentIdentity__factory } from "./StudentIdentity__factory";
